version: '3'
services:
  psql:
    image: postgres:10-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql
    environment:
      DEBUG: "false"
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  server:
    build: .
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - psql
volumes:
  database:
    driver: "local"
